# Generated by Django 5.0.6 on 2024-05-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='role',
            new_name='matricule',
        ),
    ]
